### ISSUE TITLE
 Can you put the project on cdnjs or other cdn?

### ISSUE THREAD

**Issue by dxy2233** [MetinSeylan/Vue-Socket.io#191]
The project is a bit large.
Sites with low bandwidth load are a bit slow.
Thanks.

**Comment by zgs1108** [comment]
Webpack package error， "Unexpected token: punc (() [./node_modules/vue-socket.io/dist/vue-socketio.js". In order to solve the packaging problem, add “resolve('/node_modules/vue-socket.io/dist/vue-socketio.js') ” in webpack.base.conf.js. Cause error “export 'default' (imported as 'VueSocketIO') was not found in 'vue-socket.io'” . I don't understand what caused this error, Is there any good solution?Thank you

**Comment by eyaylagul** [comment]
@dxy2233 
You can use this source 
https://unpkg.com/vue-socket.io@latest
