### ISSUE TITLE
Latest version breaks library

### ISSUE THREAD

**Issue by mikemissing** [MetinSeylan/Vue-Socket.io#250]
**Describe the bug**
When using the latest version I get the following error:
`TypeError: o.sockets.subscribe is not a function`

This is caused when I try to run `this.sockets.subscribe('name', ...)`

**Expected behavior**
The app is supposed to access the sockets via `this.sockets.` as it did in previous version

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome, Firefox

**Additional context**
Reverting to previous version 3.0.7 solved the issue.

I could not pinpoint the issue in source code due to ... minimization?

**Comment by koptelovav** [comment]
Thank you very match! You saved my day!

**Comment by huangxuewu** [comment]
i spend like 2 days to figure it out what went wrong in my latest project which create 2 days ago. all the code is the same but last project just won't work.

**Comment by kovinet** [comment]
Since last version component methods in `sockets:` don't get triggered anymore. I don't get any error, but sample methods (`connect`, `customEmit`) from example below never get triggered:

```js
    sockets: {
        connect: function () {
            console.log('socket connected')
        },
        customEmit: function (data) {
            console.log('this method was fired by the socket server. eg: io.emit("customEmit", data)')
        }
    },
```
I think it is related to original issue reported ... ?
When I downgraded to 3.0.7 is started working again.

**Comment by godtoy** [comment]
please fix it , same bug

**Comment by jianghaibo12138** [comment]
When I replace this.sockets.subscribe by this.sockets.listener.subscribe and the error disappear.

**Comment by maximkolc** [comment]
i lost all day.............. please, fix, ver 3.0.8 not work correctly

**Comment by godtoy** [comment]
this lib not support ack callback？

**Comment by lieqiang** [comment]
please fix it , same bug

**Comment by GoliafRS** [comment]
Until the bug is fixed, everyone who has a similar problem can install the version 3.0.5.

I have the same problem but this version is not broken yet.
And I don’t understand why to make such changes in the patch version.
It's breaking changes. They should be at least in a minor, and preferably a major version with explanations.

**Comment by taokanghua** [comment]
very very thank you!!!!!!!

**Comment by Antoxa1081** [comment]
Until the bug is fixed, you can use `this.sockets.io` instead `this.sockets`

**Comment by hidde-jan** [comment]
Version 3.0.9 is still broken for me, needed to revert to 3.0.7 to get it working again.

**Comment by sayhicoelho** [comment]
Latest version 3.0.9 with same bug here. I'll try @GoliafRS workaround.

**Comment by dgiangrave** [comment]
@GoliafRS is correct in the location, it originates from commit 8988085bef6bbf9ecdb5fced6b4220d5eb853bd3 "Handle more than one namespace". The changes to the mixin file do not properly add the event listeners for all configurations of the plugin, as well as it contains a number of inconsistencies with its documentation.

I had submitted a PR, #242, in March, both adding namespacing for Vuex modules as well as reverting this specific commit. For any still facing issues, I echo the suggestion to revert to `v3.0.7` until the issue is addressed.

**Comment by 1e4** [comment]
Just want to add on that I just installed the latest version `3.0.9` and it's broken, reverting to `3.0.7` **did** work. Thank you
