### ISSUE TITLE
Pinia Support

### ISSUE THREAD

**Issue by pascal-mueller** [MetinSeylan/Vue-Socket.io#331]
Is this project ever getting Pinia support, the new official store fro VueJS? Is it even still maintained?

**Comment by ghost** [comment]
@pascal-mueller personally, I'd try to create your own SocketIO service instead of relying on this plugin. Development on it is not very active and I had to [use a fork](https://github.com/kil0ba/Vue-3-Socket.io) to be compatible with Vue 3.

With the new [script setup syntax](https://vuejs.org/api/sfc-script-setup.html), it seems even more logical to move away from a Vue plugin. Here's an example on how you could do that: https://deepinder.me/creating-a-real-time-chat-app-with-vue-socket-io-and-nodejs

**Comment by pascal-mueller** [comment]
Thanks for the input.
